name: Deploy no Docker Hub

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Send Telegram Alert on Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ O deploy falhou no projeto TechApp! Verificar no GitHub Actions."

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t mayarayumihino/booktracker-pucpr .

      - name: Publish Image to DockerHub
        run: docker push mayarayumihino/booktracker-pucpr:latest
